/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stk.views.Config;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import stk.entities.Quydinh;
import stk.helper.QuyDinhHelper;
import stk.util.ShowMessage;
import stk.util.Utill;

/**
 *
 * @author chitai
 */
public class ConfigView extends javax.swing.JFrame {

    /**
     * Creates new form Quydinh
     */
    public ConfigView() {
        initComponents();
        centreWindow(this);
        initData();
    }
    Quydinh obj = new Quydinh();
  public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbLx = new javax.swing.JComboBox<>();
        txNumType = new javax.swing.JTextField();
        txtNumDate = new javax.swing.JTextField();
        txMinMoney = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cài đặt");

        btUpdate.setText("Cập nhật");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("Số ngày đáo hạn");

        jLabel5.setText("Số loại");

        jLabel7.setText("Tiền gởi tối thiểu");

        jLabel10.setText("Thay đổi lãi xuất");

        cbLx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không được thay đổi", "Được thay đổi" }));
        cbLx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btUpdate)
                                .addGap(160, 160, 160))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbLx, 0, 235, Short.MAX_VALUE)
                                    .addComponent(txMinMoney)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNumType, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumDate)
                                .addGap(1, 1, 1)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txNumType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbLx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txMinMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btUpdate)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        QuyDinhHelper ob = new QuyDinhHelper();
        if(txNumType.getText().isEmpty()){
            new ShowMessage().ShowError("Không được bỏ trống Số loại!", "Vui lòng điền dữ liệu");
            return;
        }
        if(Utill.parseInt(txNumType.getText())< 0)
        {
            new ShowMessage().ShowError("Sai định dạng kiểu số!", "Vui lòng điền dữ liệu");
        }
        if(txtNumDate.getText().isEmpty()){
            new ShowMessage().ShowError("Không được bỏ trống Số ngày!", "Vui lòng điền dữ liệu");
            return;
        }
        if(Utill.parseInt(txtNumDate.getText())< 0)
        {
            new ShowMessage().ShowError("Sai định dạng kiểu số!", "Vui lòng điền dữ liệu");
        }
        if(txMinMoney.getText().isEmpty()){
            new ShowMessage().ShowError("Không được bỏ trống Số tiền tối thiểu!", "Vui lòng điền dữ liệu");
            return;
        }
        if(Utill.parseInt(txMinMoney.getText())< 0)
        {
            new ShowMessage().ShowError("Sai định dạng kiểu số!", "Vui lòng điền dữ liệu");
        }
        
        obj.setSoLoai(Utill.parseInt(txNumType.getText()));
        obj.setSoNgayDaoHan(Utill.parseInt(txtNumDate.getText()));
        obj.setTienGoiToiThieu(Utill.parseInt(txMinMoney.getText()));
        ob.doUpdate(obj);
        this.setVisible(false);
    }//GEN-LAST:event_btUpdateActionPerformed

    private void cbLxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLxActionPerformed
            // TODO add your handling code here:
           obj.setThayDoiLaiXuat(cbLx.getSelectedIndex()==1?true:false);
    }//GEN-LAST:event_cbLxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbLx;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txMinMoney;
    private javax.swing.JTextField txNumType;
    private javax.swing.JTextField txtNumDate;
    // End of variables declaration//GEN-END:variables

    private void initData() {
         QuyDinhHelper ob = new QuyDinhHelper();
         obj = (Quydinh) ob.doSeleteById(0);
         
         txMinMoney.setText(obj.getTienGoiToiThieu() + "");
         txNumType.setText(obj.getSoLoai()+ "");
         txtNumDate.setText(obj.getSoNgayDaoHan()+ "");
         
         cbLx.setSelectedIndex(obj.isThayDoiLaiXuat()?1:0);

                 
                 
    }
}
