/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stk.views.Ticket;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.management.monitor.Monitor;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import stk.entities.Khachhang;
import stk.entities.Phieuguitien;
import stk.entities.Quydinh;
import stk.entities.Sotk;
import stk.helper.KhachHangHelper;
import stk.helper.PhieuGoiHelper;
import stk.helper.QuyDinhHelper;
import stk.helper.SoTKHelper;
import stk.util.ShowMessage;
import stk.util.Utill;
import stk.views.Saving.*;
/**
 *
 * @author Administrator
 */
public class TicketInView extends javax.swing.JFrame {
     int currentId = - 1;
     List<Sotk> stks = new ArrayList<Sotk>();
    KhachHangHelper kh = new KhachHangHelper();   
    SoTKHelper stk = new SoTKHelper();       
    PhieuGoiHelper pg = new PhieuGoiHelper();       
    Quydinh obj = new Quydinh();
    QuyDinhHelper ob = new QuyDinhHelper();
    /**
     * Creates new form TicketIn
     */
    public TicketInView() {
        initComponents();
        centreWindow(this);
        selectTicket();
        initData();
    }
  public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTextField1 = new stk.util.DateTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btLamMoi = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTienGoi = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtDate = new stk.util.DateTextField();
        cbMaSo = new javax.swing.JComboBox<>();
        txtKh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phiếu gởi tiền");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã sổ", "Tên", "Ngày gửi", "Số tiền gửi"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btLamMoi.setText("Làm mới");
        btLamMoi.setEnabled(false);
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        btSua.setText("Sửa");
        btSua.setEnabled(false);
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel14.setText("Mã sổ");

        jLabel25.setText("Khách hàng");

        jLabel26.setText("Số tiền gửi");

        jLabel29.setText("Ngày gửi");

        cbMaSo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMaSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaSoActionPerformed(evt);
            }
        });

        txtKh.setEditable(false);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel25))
                .addGap(30, 30, 30)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMaSo, 0, 259, Short.MAX_VALUE)
                    .addComponent(txtKh))
                .addGap(34, 34, 34)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienGoi)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTienGoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(cbMaSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jPanel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMaSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaSoActionPerformed
        // TODO add your handling code here:
        if(cbMaSo.getSelectedIndex() !=0 ){
            Khachhang k = (Khachhang) kh.doSeleteById(stks.get(cbMaSo.getSelectedIndex() - 1).getIdKh());
            txtKh.setText(k.getTen());
        }else txtKh.setText("");
    }//GEN-LAST:event_cbMaSoActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
         if(currentId > 0){
            new ShowMessage().ShowError( "Vui lòng làm mới trước khi thêm","Đang chọn dữ liệu!");
            return;
        }
        if(txtKh.getText().isEmpty()){
            new ShowMessage().ShowError("Vui lòng chọn mã sổ!", "Vui lòng chọn dữ liệu");
            return;
        }
        int cmnd = Utill.parseInt(txtTienGoi.getText());
        if(cmnd == -1){
            new ShowMessage().ShowError("Không đúng định dạng số!", "Vui lòng điền dữ liệu");
            return;
        }if(txtTienGoi.getText().isEmpty()){
            new ShowMessage().ShowError("Không được bỏ trống Tiền gởi!", "Vui lòng điền dữ liệu");
            return;
        }
         if(obj.getTienGoiToiThieu() > cmnd){
             new ShowMessage().ShowError("Số tiền nhỏ hơn mức quy định " + obj.getTienGoiToiThieu() , "Vui lòng điền dữ liệu");
            return;
        }
        
        Phieuguitien obj = new Phieuguitien();
        obj.setIdKh(stks.get(cbMaSo.getSelectedIndex() -1).getIdKh());
        obj.setMaSo(stks.get(cbMaSo.getSelectedIndex()-1).getMaSo());
        obj.setNgayGui(Utill.setDate(txtDate.getText()));
        obj.setSoTienGui(Utill.parseInt(txtTienGoi.getText()));
        pg.doCreate(obj);
        btLamMoiActionPerformed(null);
    }//GEN-LAST:event_btThemActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
                currentId = -1;
                cbMaSo.setSelectedIndex(0);
                txtKh.setText("");
                txtTienGoi.setText("");
                txtDate.setText(Utill.getNowDate());
                
            btLamMoi.setEnabled(false);
            btSua.setEnabled(false);
            btThem.setEnabled(true);
            selectTicket();
            initData();
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        btLamMoi.setEnabled(false);
        btSua.setEnabled(false);
        btThem.setEnabled(true);
        
         // TODO add your handling code here:
         if(currentId < 0){
            new ShowMessage().ShowError( "Vui lòng chọn dữ liệu cần sửa","Chọn dữ liệu!");
            return;
        }
        if(txtKh.getText().isEmpty()){
            new ShowMessage().ShowError("Vui lòng chọn mã sổ!", "Vui lòng chọn dữ liệu");
            return;
        }
        int cmnd = Utill.parseInt(txtTienGoi.getText());
        if(cmnd == -1){
            new ShowMessage().ShowError("Không đúng định dạng số!", "Vui lòng điền dữ liệu");
            return;
        }if(txtTienGoi.getText().isEmpty()){
            new ShowMessage().ShowError("Không được bỏ trống Tiền gởi!", "Vui lòng điền dữ liệu");
            return;
        }
        if(obj.getTienGoiToiThieu() > cmnd){
             new ShowMessage().ShowError("Số tiền nhỏ hơn mức quy định " + obj.getTienGoiToiThieu() , "Vui lòng điền dữ liệu");
            return;
        }
        
        Phieuguitien obj = new Phieuguitien();
        obj.setId(currentId);
        obj.setIdKh(stks.get(cbMaSo.getSelectedIndex() -1 ).getIdKh());
        obj.setMaSo(stks.get(cbMaSo.getSelectedIndex() -1 ).getMaSo());
        obj.setNgayGui(Utill.setDate(txtDate.getText()));
        obj.setSoTienGui(Utill.parseInt(txtTienGoi.getText()));
        pg.doUpdate(obj);
        btLamMoiActionPerformed(null);
    }//GEN-LAST:event_btSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketInView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JComboBox<String> cbMaSo;
    private stk.util.DateTextField dateTextField1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable7;
    private stk.util.DateTextField txtDate;
    private javax.swing.JTextField txtKh;
    private javax.swing.JTextField txtTienGoi;
    // End of variables declaration//GEN-END:variables
 private void selectTicket() {
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
        List<Phieuguitien> resultList = pg.doSeleteAll(null);
        try{
           while(model.getRowCount() > 0){
           model.removeRow(0);
        }}catch(Exception e){}
        for (Phieuguitien item : resultList) {
              Khachhang k = (Khachhang) kh.doSeleteById(item.getIdKh());
              model.addRow(new Object[]{item.getId(),item.getMaSo(), k.getTen(), item.getNgayGui(), item.getSoTienGui()});
        }
        jTable7.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent event) {
            try{
                currentId = Integer.parseInt(jTable7.getValueAt(jTable7.getSelectedRow(), 0).toString());
                cbMaSo.setSelectedIndex(1 + getIndex(Utill.parseInt(jTable7.getValueAt(jTable7.getSelectedRow(), 0).toString())));
                txtKh.setText(jTable7.getValueAt(jTable7.getSelectedRow(), 2).toString());
                txtDate.setText(Utill.showDate(jTable7.getValueAt(jTable7.getSelectedRow(), 3).toString()));
                txtTienGoi.setText(jTable7.getValueAt(jTable7.getSelectedRow(), 4).toString());

                btLamMoi.setEnabled(true);
                btSua.setEnabled(true);
                btThem.setEnabled(false);

            }catch(Exception e){
                currentId = -1;
                cbMaSo.setSelectedIndex(0);
                txtKh.setText("");
                txtTienGoi.setText("");
                txtDate.setText(Utill.getNowDate());
            }
        }
    });
    }
    private int getIndex(int toString) {
            for (int i = 0; i < stks.size(); i++) {
                if(stks.get(i).getId()== (toString))
                    return i;
            }
            return 0;
        }
    private void initData() {
        stks = stk.doSeleteAll(null);

        String[] sltk = new String[stks.size() + 1];
        
        sltk[0] = "Chọn dữ liệu";
        for (int i = 1 ; i< stks.size() + 1; i++) {
            sltk[i] = stks.get(i - 1).getMaSo();
        }
        txtDate.setText(Utill.getNowDate());
        obj = (Quydinh) ob.doSeleteById(0);
        cbMaSo.setModel(new javax.swing.DefaultComboBoxModel<>(sltk));
    }
}
