package stk.entities;
// Generated Apr 30, 2019 10:15:30 AM by Hibernate Tools 4.3.1



/**
 * Loaitietkiem generated by hbm2java
 */
public class Loaitietkiem  implements java.io.Serializable {


     private Integer id;
     private String tenLoai;
     private float laiXuat;

    public Loaitietkiem() {
    }

    public Loaitietkiem(String tenLoai, float laiXuat) {
       this.tenLoai = tenLoai;
       this.laiXuat = laiXuat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public float getLaiXuat() {
        return this.laiXuat;
    }
    
    public void setLaiXuat(float laiXuat) {
        this.laiXuat = laiXuat;
    }




}


