package stk.entities;
// Generated Apr 8, 2019 2:27:23 PM by Hibernate Tools 4.3.1



/**
 * Loaitietkiem generated by hbm2java
 */
public class Loaitietkiem  implements java.io.Serializable {


     private Integer id;
     private String tenLoai;

    public Loaitietkiem() {
    }

    public Loaitietkiem(String tenLoai) {
       this.tenLoai = tenLoai;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }




}


