package stk.entities;
// Generated Apr 8, 2019 2:27:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieuguitien generated by hbm2java
 */
public class Phieuguitien  implements java.io.Serializable {


     private Integer id;
     private int idKh;
     private int soTienGui;
     private Date ngayGui;

    public Phieuguitien() {
    }

    public Phieuguitien(int idKh, int soTienGui, Date ngayGui) {
       this.idKh = idKh;
       this.soTienGui = soTienGui;
       this.ngayGui = ngayGui;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdKh() {
        return this.idKh;
    }
    
    public void setIdKh(int idKh) {
        this.idKh = idKh;
    }
    public int getSoTienGui() {
        return this.soTienGui;
    }
    
    public void setSoTienGui(int soTienGui) {
        this.soTienGui = soTienGui;
    }
    public Date getNgayGui() {
        return this.ngayGui;
    }
    
    public void setNgayGui(Date ngayGui) {
        this.ngayGui = ngayGui;
    }




}


