package stk.entities;
// Generated Apr 8, 2019 2:27:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieuruttien generated by hbm2java
 */
public class Phieuruttien  implements java.io.Serializable {


     private Integer id;
     private int idKh;
     private int soTienRut;
     private Date ngayRut;

    public Phieuruttien() {
    }

    public Phieuruttien(int idKh, int soTienRut, Date ngayRut) {
       this.idKh = idKh;
       this.soTienRut = soTienRut;
       this.ngayRut = ngayRut;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdKh() {
        return this.idKh;
    }
    
    public void setIdKh(int idKh) {
        this.idKh = idKh;
    }
    public int getSoTienRut() {
        return this.soTienRut;
    }
    
    public void setSoTienRut(int soTienRut) {
        this.soTienRut = soTienRut;
    }
    public Date getNgayRut() {
        return this.ngayRut;
    }
    
    public void setNgayRut(Date ngayRut) {
        this.ngayRut = ngayRut;
    }




}


