package stk.entities;
// Generated Apr 8, 2019 2:27:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sotk generated by hbm2java
 */
public class Sotk  implements java.io.Serializable {


     private Integer id;
     private int idKh;
     private int loaiTk;
     private Date ngayMoSo;
     private int soTienGui;

    public Sotk() {
    }

    public Sotk(int idKh, int loaiTk, Date ngayMoSo, int soTienGui) {
       this.idKh = idKh;
       this.loaiTk = loaiTk;
       this.ngayMoSo = ngayMoSo;
       this.soTienGui = soTienGui;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdKh() {
        return this.idKh;
    }
    
    public void setIdKh(int idKh) {
        this.idKh = idKh;
    }
    public int getLoaiTk() {
        return this.loaiTk;
    }
    
    public void setLoaiTk(int loaiTk) {
        this.loaiTk = loaiTk;
    }
    public Date getNgayMoSo() {
        return this.ngayMoSo;
    }
    
    public void setNgayMoSo(Date ngayMoSo) {
        this.ngayMoSo = ngayMoSo;
    }
    public int getSoTienGui() {
        return this.soTienGui;
    }
    
    public void setSoTienGui(int soTienGui) {
        this.soTienGui = soTienGui;
    }




}


