package stk.entities;
// Generated Jun 16, 2019 2:23:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sotk generated by hbm2java
 */
public class Sotk  implements java.io.Serializable {


     private Integer id;
     private String maSo;
     private int idKh;
     private int loaiTk;
     private Date ngayMoSo;
     private int soTienGui;
     public String Ten;
     public String Loai;
    public Sotk() {
    }

    public Sotk(String maSo, int idKh, int loaiTk, Date ngayMoSo, int soTienGui) {
       this.maSo = maSo;
       this.idKh = idKh;
       this.loaiTk = loaiTk;
       this.ngayMoSo = ngayMoSo;
       this.soTienGui = soTienGui;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMaSo() {
        return this.maSo;
    }
    
    public void setMaSo(String maSo) {
        this.maSo = maSo;
    }
    public int getIdKh() {
        return this.idKh;
    }
    
    public void setIdKh(int idKh) {
        this.idKh = idKh;
    }
    public int getLoaiTk() {
        return this.loaiTk;
    }
    
    public void setLoaiTk(int loaiTk) {
        this.loaiTk = loaiTk;
    }
    public Date getNgayMoSo() {
        return this.ngayMoSo;
    }
    
    public void setNgayMoSo(Date ngayMoSo) {
        this.ngayMoSo = ngayMoSo;
    }
    public int getSoTienGui() {
        return this.soTienGui;
    }
    
    public void setSoTienGui(int soTienGui) {
        this.soTienGui = soTienGui;
    }




}


