package stk.entities;
// Generated Apr 30, 2019 10:15:30 AM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private Integer id;
     private String tenTaiKhoan;
     private String hoTen;
     private String matKhau;

    public Taikhoan() {
    }

    public Taikhoan(String tenTaiKhoan, String hoTen, String matKhau) {
       this.tenTaiKhoan = tenTaiKhoan;
       this.hoTen = hoTen;
       this.matKhau = matKhau;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenTaiKhoan() {
        return this.tenTaiKhoan;
    }
    
    public void setTenTaiKhoan(String tenTaiKhoan) {
        this.tenTaiKhoan = tenTaiKhoan;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }




}


